# Generated by Django 4.1 on 2022-10-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0002_pelicula_usuario_delete_cliente_delete_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
